import msh_reg from '../assets/images/toppings/topping_Mushroom_ML_reg.webp';
import spn_reg from '../assets/images/toppings/topping_Spinach_Fresh_ML_reg.webp';
import oni_reg from '../assets/images/toppings/topping_Onion_red_ML_reg.webp';
import olv_reg from '../assets/images/toppings/topping_Olives_black_ML_reg.webp';
import grp_reg from '../assets/images/toppings/topping_GreenBellPepper_ML_reg.webp';
import bnp_reg from '../assets/images/toppings/topping_BananaPepper_ML_reg.png';
import pnp_reg from '../assets/images/toppings/topping_Pineapple_ML_reg.webp';
import jlp_reg from '../assets/images/toppings/topping_Jalepeno_ML_reg.webp';
import tom_reg from '../assets/images/toppings/topping_Tomato_ML_reg.png';
import msh_extra from '../assets/images/toppings/topping_Mushroom_ML_extra.webp';
import spn_extra from '../assets/images/toppings/topping_Spinach_Fresh_ML_extra.webp';
import oni_extra from '../assets/images/toppings/topping_Onion_red_ML_extra.png';
import olv_extra from '../assets/images/toppings/topping_Olives_black_ML_extra.webp';
import grp_extra from '../assets/images/toppings/topping_GreenBellPepper_ML_extra.webp';
import bnp_extra from '../assets/images/toppings/topping_BananaPepper_ML_extra.png';
import pnp_extra from '../assets/images/toppings/topping_Pineapple_ML_extra.webp';
import jlp_extra from '../assets/images/toppings/topping_Jalepeno_ML_extra.webp';
import tom_extra from '../assets/images/toppings/topping_Tomato_ML_extra.png';

export const mushroom_reg = msh_reg;
export const spinach_reg = spn_reg;
export const onions_reg = oni_reg;
export const olives_reg = olv_reg;
export const green_pepper_reg = grp_reg;
export const banana_pepper_reg = bnp_reg;
export const pineapple_reg = pnp_reg;
export const jalapeno_reg = jlp_reg;
export const tomato_reg = tom_reg;
export const mushroom_extra = msh_extra;
export const spinach_extra = spn_extra;
export const onions_extra = oni_extra;
export const olives_extra = olv_extra;
export const green_pepper_extra = grp_extra;
export const banana_pepper_extra = bnp_extra;
export const pineapple_extra = pnp_extra;
export const jalapeno_extra = jlp_extra;
export const tomato_extra = tom_extra;
